const allFeatures = {
  create_engagement: 'create_engagement',
  edit_engagement: 'edit_engagement',
  delete_engagement: 'delete_engagement',
  read_engagement: 'read_engagement',
  create_case_study: 'create_case_study',
  read_case_study: 'read_case_study',
  delete_case_study: 'delete_case_study',
  edit_case_study: 'edit_case_study',
  search_user: 'search_user',
  search_case_study: 'search_case_study',
  search_engagement: 'search_engagement',
  read_skills: 'read_skills',
  create_skills: 'create_skills',
  edit_skills: 'edit_skills',
  delete_skills: 'delete_skills',
  write_staffing_entry: 'write_staffing_entry',
  upload_excel: 'upload_excel',
  upload_image_case_study: 'upload_image_case_study',
  upload_image_engagement: 'upload_image_engagement',
  upload_image_user: 'upload_image_user',
  read_user: 'read_user',
  create_user: 'create_user',
  delete_user: 'delete_user',
  edit_user: 'edit_user',
  create_skill_self: 'create_skill_self',
  edit_skill_self: 'edit_skill_self',
  edit_user_self: 'edit_user_self',
  upload_image_user_self: 'upload_image_user_self',
};

module.exports = allFeatures;
